# Generated by Django 5.0.4 on 2024-04-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('tema', models.CharField(max_length=100, verbose_name='тема')),
                ('description', models.TextField(verbose_name='описание')),
                ('zadacha', models.TextField(blank=True, null=True, verbose_name='задача')),
                ('image', models.ImageField(blank=True, null=True, upload_to='documents_images/', verbose_name='изображение')),
                ('link_youtube', models.CharField(max_length=200, verbose_name='ссылка от ютуба на видео')),
                ('reshenie', models.TextField(verbose_name='решение задачи')),
            ],
            options={
                'verbose_name': 'документ',
                'verbose_name_plural': 'документы',
            },
        ),
        migrations.CreateModel(
            name='Topics_Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('document', models.ManyToManyField(related_name='topics', to='core.documentation', verbose_name='документы')),
            ],
            options={
                'verbose_name': 'тема',
                'verbose_name_plural': 'темы',
            },
        ),
    ]
