# Generated by Django 5.0.4 on 2024-04-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_documentation_topics_documentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя программиста')),
                ('image', models.ImageField(blank=True, null=True, upload_to='developer_images/', verbose_name='изображение')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('instagram', models.TimeField(verbose_name='instagram')),
                ('description', models.CharField(max_length=300, verbose_name='описание')),
                ('status', models.CharField(max_length=100, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'программист',
                'verbose_name_plural': 'программисты',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='вопрос')),
                ('var1', models.TextField(verbose_name='вариант1')),
                ('var2', models.TextField(verbose_name='вариант2')),
                ('var3', models.TextField(verbose_name='вариант3')),
                ('answer', models.TextField(verbose_name='правильный ответ')),
                ('level', models.CharField(max_length=100, verbose_name='уровень')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
            },
        ),
        migrations.CreateModel(
            name='Topics_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя теста')),
                ('level', models.CharField(max_length=100, verbose_name='уровень')),
                ('test', models.ManyToManyField(related_name='tests', to='core.test', verbose_name='тесты')),
            ],
            options={
                'verbose_name': 'тест',
                'verbose_name_plural': 'тесты',
            },
        ),
    ]
