# Generated by Django 5.0.4 on 2024-04-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aboutus_test_topics_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='имя вопроса'),
        ),
    ]
