# Generated by Django 5.0.4 on 2024-04-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_test_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topics_documentation',
            options={'verbose_name': 'подтема', 'verbose_name_plural': 'подтемы'},
        ),
        migrations.AlterField(
            model_name='topics_documentation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='имя подтемы'),
        ),
        migrations.CreateModel(
            name='All_Topics_Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя сборника')),
                ('document', models.ManyToManyField(related_name='all_topics', to='core.topics_documentation', verbose_name='подтемы')),
            ],
            options={
                'verbose_name': 'сборник',
                'verbose_name_plural': 'сборники',
            },
        ),
    ]
